---
deploy:
  args:
    branch: master
  class: Statocles::Deploy::Git
page_app:
  args:
    store: page
    url_root: /page
  class: Statocles::App::Plain
page_app_projects:
  args:
    store: page
    url_root: /projects
  class: Statocles::App::Plain
site:
  args:
    apps:
      page:
        $ref: page_app
      static:
        $ref: static_app
      projects:
        $ref: page_app_projects
    base_url: http://cmdcolin.github.io
    deploy:
      $ref: deploy
    index: page
    nav:
      main:
        - href: /
          title: About
        - href: /projects
          title: Projects
        - href: https://github.com/cmdcolin/
          title: GitHub
        - href: https://twitter.com/cmdcolin/
          title: Twitter
    theme:
      $ref: theme
    title: Stationary Module
  class: Statocles::Site
  on:
    - build:
        $class: Statocles::Plugin::LinkCheck
        $sub: check_pages
theme:
  args:
    store: theme
  class: Statocles::Theme
