---
deploy:
  args:
    branch: master
  class: Statocles::Deploy::Git
page_app:
  class: Statocles::App::Basic
  args:
    store: site/
    url_root: /
blog_app:
  $class: Statocles::App::Blog
  store: "blog"
  url_root: /blog
site:
  args:
    apps:
      blog:
        $ref: blog_app
      page:
        $ref: page_app
      static:
        $ref: static_app
    deploy:
      $ref: deploy
    index: /index.html
    nav:
      main:
        - href: /
          title: About
        - href: /blog
          title: Blog
        - href: /projects
          title: Projects
        - href: /links
          title: Links
        
    title: Stationary Module
    data:
      google_analytics_id: 'UA-59273647-1'
  class: Statocles::Site
static_app:
  args:
    store: static
    url_root: /static
  class: Statocles::App::Basic
